### PR TITLE
adding basic anchor support

### PR DESCRIPTION
**Pull request by thshdw**
Basic support for anchors, eventually “-X” should be used see
/etc/pf.conf

```
#
# Default PF configuration file.
#
# This file contains the main ruleset, which gets automatically loaded
# at startup.  PF will not be automatically enabled, however.  Instead,
# each component which utilizes PF is responsible for enabling and disabling
# PF via -E and -X as documented in pfctl(8).  That will ensure that PF
# is disabled only when the last enable reference is released.
#
# Care must be taken to ensure that the main ruleset does not get flushed,
# as the nested anchors rely on the anchor point defined here. In addition,
# to the anchors loaded by this file, some system services would dynamically
# insert anchors into the main ruleset. These anchors will be added only when
# the system service is used and would removed on termination of the service.
#
# See pf.conf(5) for syntax.
#
```

### CODE REVIEW

**Comment by seanzxx** [comment]
@thshdw thank you very much.  
I feel it really weird using the 'com.apple/sshuttle' as anchor name.

**Comment by thshdw** [comment]
@seanzxx @brianmay 
I'm using com.apple/sshuttle as `com.apple` is already loaded by pf.conf

from pf.conf

```
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
```

so com.apple/sshuttle allows us to make a shuttle anchor and we don't have to `load anchor` 

If we are to have proper anchor support in OS X I feel we should use the `pfctl -X token` method to achieve that. This is what pf.conf says 

```
# Default PF configuration file.
#
# This file contains the main ruleset, which gets automatically loaded
# at startup.  PF will not be automatically enabled, however.  Instead,
# each component which utilizes PF is responsible for enabling and disabling
# PF via -E and -X as documented in pfctl(8).  That will ensure that PF
# is disabled only when the last enable reference is released.
```

This what apple recommends. Its also pretty cool as you can then have two or more instances of PF running... Lets say the AirDrop anchor is running and I have sshuttle running as well.

```
#
# AirDrop anchor point.
#
anchor "200.AirDrop/*"
```

using -X will stop pfctl for only sshuttle and keep the airdrop anchor running.

**Comment by seanzxx** [comment]
@thshdw
Yes, the way works very well. 
What I'm not feeling well is the anchor name. 
I think the 'com.apple/*' should be used by Apple products.

**Comment by thshdw** [comment]
@seanzxx That makes sense. Using com.apple was cheating a bit to take advantage of the pre loaded anchor

**Comment by thshdw** [comment]
@seanzxx Closing my pull request. I think the only thing left is to do an OS check as `-E` and `-X`` are not in other versions of pfcl. See my comments on the [other thread.](https://github.com/sshuttle/sshuttle/pull/4) Thanks again for your OSX contributions to sshuttle.

**Pull request closed without merging**
